!
!  incrementTest.f90
!
!  Fortran Console Application 
!  Generated by PGI Visual Fortran(R)
!  1/27/2016 1:22:21 AM
!  Autor: Roberto Carlos Sales UFF-PPGEM
!
program incrementTest
use cudafor
use simpleOps_m
implicit none
integer , parameter :: n = 2567
integer :: a(n), b
integer , device :: a_d(n)   ! variável inteira e do tipo device
a = 1
b = 3
a_d = a
call increment <<<1,n>>>(a_d , b)  ! este chevron especifica um bloco em n=256 threads neste exemplo
a = a_d							   ! passagem do valor de a_d (device) para a (host)
if (any(a /= 4)) then
write (* ,*) '**** Programa contém falha **** ', n
else
write (* ,*) 'Programa funciona ', n
endif
end program incrementTest
